{% set name = "django-livesettings3" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-livesettings3-{{ version }}.tar.gz
  sha256: 8c485fc48c779fe6f248a71175be24ff4489a05c9500129adf1764e43529a0b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=1.8,<3
    - django-keyedcache3
    - python >=3.6

test:
  imports:
    - livesettings
    - livesettings.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kunaldeo/django-livesettings3/
  summary: Python 3 port of django-livesettings
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
